### ISSUE TITLE
Compatibility with Python 3.11.2 ?

### ISSUE THREAD

**Issue by schwentker** [autonity/aut#107]
Attempting to install via:

pipx install git+https://github.com/autonity/aut

I'm getting an error around version of python 3.11.2

ERROR: Package 'autonity-py' requires a different Python: 3.11.2 not in '<3.11,>=3.8'

**Comment by rmsams** [comment]
Support for python 3.11 was [temporarily removed in v0.1.3](https://github.com/autonity/aut/releases/tag/v0.1.3). Can you try installing it with a compatible version of Python? 

We're working to towards broader python version coverage, but for now 3.11 is not supported.

**Comment by cmjc** [comment]
I'm running it on 3.10 atm on MacOS & Ubuntu.

`pipx install --python $(which python3.10) git+ssh://git@github.com/autonity/aut.git`

**Comment by noandrea** [comment]
support for v3.11 has been added in the latest release [v2.0.0](https://github.com/autonity/aut/releases/tag/v0.2.0)
