### ISSUE TITLE
Unexpected behavior of th command "aut validator info --validator" when the address is not a validator

### ISSUE THREAD

**Issue by jfaiza** [autonity/aut#113]
When we use the command "aut validator info --validator" with an address which is not a validator it returns this response:
  {
    "treasury": "0x0000000000000000000000000000000000000000",
    "addr": "0x0000000000000000000000000000000000000000",
    "enode": "",
    "commission_rate": 0,
    "bonded_stake": 0,
    "total_slashed": 0,
    "liquid_contract": "0x0000000000000000000000000000000000000000",
    "liquid_supply": 0,
    "registration_block": 0,
    "state": 0
  }

It should return that the address is not a validator instead of this response.

**Comment by noandrea** [comment]
shipped in [v0.2.0](https://github.com/autonity/aut/releases/tag/v0.2.0)
