### ISSUE TITLE
Response of "aut account verify-signature --help"

### ISSUE THREAD

**Issue by jfaiza** [autonity/aut#114]
In the response of "aut account verify-signature --help" we show an extre Grave Accent " ` "   after    " Verify that the signature in SIGNATURE_FILE "

Exemple :
  - command: 
      $ aut account verify-signature --help

  - Response Usage: 
      aut account verify-signature [OPTIONS] MESSAGE SIGNATURE_FILE

      Verify that the signature in SIGNATURE_FILE` is valid for the message
      MESSAGE, signed by the owner of the FROM address. Signature must be
      contained in a file.

**Comment by aiman** [comment]
Done in v0.3.0
