### ISSUE TITLE
Aut installation issue information

### ISSUE THREAD

**Issue by vkbytes** [autonity/aut#121]
While installing the `aut` commandline you may see this issue where the key to github.com cannot be determined and your installation will be stuck and will error out with the following error
```
The authenticity of host 'github.com (140.82.121.4)' can't be established.'
ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
This key is not known by any other names
⣽ determining package name from 'git+ssh://git@github.com/autonity/aut.git'
  error: subprocess-exited-with-error

  × git clone --filter=blob:none --quiet 'ssh://****@github.com/autonity/aut.git' /private/var/folders/bs/tnv_697n0_x1nt1f1gc314yh0000gn/T/pip-req-build-fs7n3791 did not run successfully.
  │ exit code: 128
  ╰─> [5 lines of output]
      Host key verification failed.
      fatal: Could not read from remote repository.

      Please make sure you have the correct access rights
      and the repository exists.
      [end of output]
   ```

**Comment by vkbytes** [comment]
The quick fix to this problem is to scan all the github keys and add them to your `~/.ssh/known_hosts` file. This can be done with `ssh-keyscan` this little information is not there on the docs page but I guess people can come across this issue on every new installation. 
To fix this run:
```
ssh-keyscan github.com >> ~/.ssh/known_hosts
```
You should see an output similar to 
```
ssh-keyscan github.com >> ~/.ssh/known_hosts
# github.com:22 SSH-2.0-babeld-1614812c
# github.com:22 SSH-2.0-babeld-1614812c
# github.com:22 SSH-2.0-babeld-1614812c
# github.com:22 SSH-2.0-babeld-1614812c
```

**Comment by noandrea** [comment]
thanks @vkbytes, 
the issue you are describing may appear when using the ssh url of the repo (git+ssh://git@...) instead of the https url as described in the project's README:

```console
pipx install git+https://github.com/autonity/aut.git
```
