### ISSUE TITLE
aut validator info throws OverflowError: Python int too large to convert to C ssize_t

### ISSUE THREAD

**Issue by DAICers** [autonity/aut#130]
**Bug**
Trying to call the `aut validator info --validator 0x31870f96212787D181B3B2771F58AF2BeD0019Aa` throws `OverflowError: Python int too large to convert to C ssize_t`.

I think the bug is probably located in autonity.py (https://github.com/autonity/aut/blob/c033d3245b344ba959c6a55a0eacb60afbd8a594/aut/commands/validator.py#L62)

**Output**
```
aut validator info --validator 0x31870f96212787D181B3B2771F58AF2BeD0019Aa
OverflowError: Python int too large to convert to C ssize_t
```

**aut version**
` aut --version
aut, version 0.2.0`

**Comment by aiman** [comment]
You need to use the latest development build of `v0.3.x`, which is currently `v0.3.0.dev4`:
https://github.com/autonity/aut/releases/tag/v0.3.0.dev4

Please upgrade and re-open this if the problem persists.
