### ISSUE TITLE
Add command to call CDP position status (cdps)

### ISSUE THREAD

**Issue by cmjc** [autonity/aut#133]
CDP's can be viewed and itneracted with using the https://docs.autonity.org/reference/api/asm/stabilization/ interface.

A CDP's current position status can be viewed by calling the `cdps` variable which is defined as a public variable and so a public getter method is defined for it when the contract is compiled.

It would be nice to have an explicit function call to return a CDP's position status. This would be easier than having to do an `aut contract call` command specifying the contract's ABI.

**Comment by aiman** [comment]
Closed in favor of more general #134

**Comment by cmjc** [comment]
OK.
