### ISSUE TITLE
Problen in the path returned by the command "aut account list" when we use the option  --with-files

### ISSUE THREAD

**Issue by jfaiza** [autonity/aut#140]
Hello,

I noticed a problem in the path returned by the command "aut account list" when we use the option "--with-files".
We have an extra slash in the returned Path of key files.

To regenerate the bug: 
 **command:** aut account list -s /home/autonity/keyfiles --with-files
  **Result:**    0xADDRESS  /home/autonity/keyfiles**//**aos.key

**Comment by aiman** [comment]
I was not able to reproduce this issue with `aut` `v0.3.0`. The printed paths do not contain additional slash by default. Only when the keystore path specified with `-s` or `--keystore` contains additional slashes, the output path will contain those extra slashes.

**Comment by jfaiza** [comment]
Yes it's true. I did more tests.
But I think this problem needs to be managed, because using linux autocompletion it initializes the path with this slash.
The result should return a correct path.

**Comment by aiman** [comment]
This is not a defect, the behavior of the tool is correct and is consistent with POSIX specification. I refer you to IEEE Std 1003.1-2017 for further reading.
