### ISSUE TITLE
Result of the command "aut validator info" when we put an address which is not an address of a valid validator

### ISSUE THREAD

**Issue by jfaiza** [autonity/aut#142]
Hello,

The result of the command "aut validator info --validator 0xADDRESS" when we put an address which is not an address of a valid validator : 
`web3.exceptions.ContractLogicError: execution reverted: validator not registered`

Shouldn't it just return "**Validator not registered**" instead of this result `web3.exceptions.ContractLogicError: execution reverted: validator not registered` ?

**Comment by aiman** [comment]
This is the intended behavior
