### ISSUE TITLE
Question about the difference of 2 options of the command "aut protocal"

### ISSUE THREAD

**Issue by jfaiza** [autonity/aut#144]
Hello,

The command `aut protocol` have 2 options `get-last-epoch-block` and `last-epoch-block`.
What is the difference of those 2 options ? they have the same behavior. Both return the last block of the last epoch.

Should you keep just one?

**Comment by aiman** [comment]
The goal was to expose all possible Autonity Contract calls, see for example https://github.com/autonity/aut/commit/32ed653 by way of https://github.com/autonity/autonity.py/commit/4a39ec3. So the current functionality is working as intended. However, we may review this in future to provide more ergonomic UI.
