### ISSUE TITLE
Description of the command "lntn-balances" when we use "aut account -h"

### ISSUE THREAD

**Issue by jfaiza** [autonity/aut#152]
The description of the command "lntn-balances" when we use "aut account -h" is not correct.
It desplays "Print the current balance of the given account." 

![image](https://github.com/autonity/aut/assets/79405564/c390e875-dd2a-42a7-8197-2f2b2aa8d2f1)

I think it should display "Print all Liquid Newton balances of the given account"

**Comment by aiman** [comment]
Fixed in develop branch.
