### ISSUE TITLE
Quote to remove in the description of the help of the command "aut protocol get-committee"

### ISSUE THREAD

**Issue by jfaiza** [autonity/aut#153]
Quote to remove in the description of the help of the command   "aut protocol  get-committee"

![image](https://github.com/autonity/aut/assets/79405564/5683a838-a619-4b1f-a5ff-60c4c06eaf80)

and 

![image](https://github.com/autonity/aut/assets/79405564/fa441355-ea1c-4e30-943b-6f53e13be3da)

**Comment by aiman** [comment]
Fixed in aaf7bfe
