### ISSUE TITLE
Errors in the response of the command "aut protocol config"

### ISSUE THREAD

**Issue by jfaiza** [autonity/aut#162]
hi,

I noticed that the values ​​of these fields in the response of the command "aut protocol config" are not correct : 
  -  epoch_period
  -  block_period
  -  committee_size

Below is an example of the response : 
![aut_protocol_config](https://github.com/autonity/aut/assets/79405564/97d6fb67-8ae0-4422-bc8d-8d3d96bbd482)

**Comment by aiman** [comment]
You may be using an incompatible version of the Autonity CLI. Please ensure are using `v0.5.0` and then try to reproduce the issue.

**Comment by jfaiza** [comment]
Yes, you are right
I updated Autonity CLI. Now I Have the correct response.
Thanks.
